apiVersion: v1
kind: Route
metadata:
  name: ${project.artifactId}
spec:
  host: appdev.openshift.io
  path: "/docs"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ${project.artifactId}
